# Generated by Django 4.2 on 2023-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название задания', max_length=50, verbose_name='Название задания')),
                ('is_complete', models.BooleanField(default=False, help_text='Название задания', verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Задания',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
